name: New Task
description: New task
labels: []
type: task
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the task
      placeholder: What needs to be done?
    validations:
      required: true
  - type: checkboxes
    id: area
    attributes:
      label: Area
      description: Backend/Frontend
      options:
        - label: backend
        - label: frontend
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Severity
      options:
        - minor
        - major
    validations:
      required: true
  - type: textarea
    id: report-back-to
    attributes:
      label: Report back to
      description: Report back to
      placeholder: Who should be informed about the task when completed?
    validations:
      required: false
