name: Issues Created Workflow

on:
  workflow_call:

jobs:
  call-workflow:
    name: Issues Created
    uses: coolshop-com/.github/.github/workflows/issues-auto-add-to-project.yaml@main
    secrets: inherit
