name: Issues Created Workflow

on:
  issues:
    types:
      - opened

jobs:
  call-workflow:
    uses: coolshop-com/.github/.github/workflows/issues-auto-add-to-project.yaml@main
    secrets:
      github-token: ${{ secrets.ADD_TO_GITHUB_TOKEN }}
