name: Issues Created Workflow

on:
  workflow_call:

jobs:
  call-workflow:
    name: Issues Created
    uses: coolshop-com/.github/.github/workflows/issues-auto-add-to-project.yaml@main
    secrets: inherit

  call-workflow-add-labels:
    name: Add labels to issue
    uses: coolshop-com/.github/.github/workflows/issues-add-labels.yaml@main
    secrets: inherit
